# This is a basic workflow to help you get started with Actions

name: Update page

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_app:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
#     - name: Run script file
#       run: |
#          chmod +x ./scripts/update.sh
#          ./scripts/update.sh     
    - name: Commit results
      run: |
        cat concerts.csv | python -c 'import csv, json, sys; print(json.dumps([dict(r) for r in csv.DictReader(sys.stdin)]))' > src/data/concerts.json
        git add -A
        git commit -m 'data updated!' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
